version: "3"
services:
  react-app:
    build: ./frontend
    ports:
      - 3000:8080
  node-app:
    build: ./backend
    ports:
      - 4001:8081
    environment:
      - ENV PORT=8081
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - TOKEN_EXPIRATION_TIME=24h
      - TOKEN_SECRET=${TOKEN_SECRET}

  redis-server:
    image: redis/redis-stack:latest
    volumes:
      - myvol1:/data
    ports:
      - 6380:6379
      - 8001:8001

volumes:
  myvol1:
